### ISSUE TITLE
flowdoc api returned: 404 Not Found

### ISSUE THREAD

**Issue by alin-simionoiuDE** [jones2026/drone-flowdock#17]
what am i doing wrong here?

```
  - name: Report Failure in Flowdoc
    image: jones2026/drone-flowdock
    settings:
      message: ":red_circle: Drone Build Failed :point_right: ${DRONE_BUILD_LINK}"
      flow_token: a30f9d
    when:
      status:
        - failure
```

obviously the `flow_token` there is not the actual token and i'm not using `from_secret`

the error i see in drone is
`Failed to post message, flowdock api returned: 404 Not Found`
